# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photosletterrecipients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='article_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.DeleteModel(
            name='tags',
        ),
    ]
