# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20190325_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
